name: ogusa-dev
channels:
- conda-forge
dependencies:
- python>=3.7.7
- mkl>=2020.2
- numpy<=1.21.2
- psutil
- scipy>=1.5.0
- pandas>=1.2.5
- matplotlib
- dask>=2.30.0
- dask-core>=2.30.0
- distributed>=2.30.1
- paramtools>=0.15.0
- taxcalc>=3.0.0
- sphinx>=3.5.4
- sphinx-book-theme>=0.1.3
- pip
- pytest>=6.0
- pytest-pep8
- pytest-xdist
- pycodestyle
- pylint
- coverage
- requests
- xlwt
- openpyxl
- statsmodels
- linearmodels
- rpy2
- black
- pip:
  - jupyter-book>=0.9.1
  - cs-kit
  - cs2tc
  - pandas-datareader
  - git+https://github.com/PSLmodels/OG-Core.git
