name: ogusa-dev
channels:
- conda-forge
dependencies:
- python>=3.7.7,<3.12
- numpy
- setuptools
- wheel
- numba>=0.54
- scipy>=1.7.1
- pandas>=1.2.5
- matplotlib
- dask>=2.30.0
- dask-core>=2.30.0
- distributed>=2.30.1
- paramtools>=0.15.0
- taxcalc>=3.0.0
- sphinx>=3.5.4
- sphinx-book-theme>=0.1.3
- jupyter-book>=0.11.3
- pytest>=6.0
- pytest-cov
- pytest-xdist
- pylint
- coverage
- requests
- xlwt
- statsmodels
- linearmodels
- black>=24.1.1
- pip
- pip:
  - rpy2>=3.5.12
  - openpyxl>=3.1.2
  - cs-kit
  - cs2tc
  - pandas-datareader
  - ogcore
